config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'welcome/index'
  root 'welcome#index'
  
  
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
   
   resources :accounts
   resources :pages
   
  get "/pages/:page" => "pages#show"

   
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    
    validates :goal, presence: true
    validates :time, presence: true
    validates :motivation, presence: true
    validates :plan, presence: true
    validates :hoursPerDay, presence: true
    validates :daysPerWeek, presence: true
    
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :accounts
    
    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    before_save { self.email = email.downcase }
    
    validates :name,
        presence: true,
        length: { maximum: 12 }
    
    validates :email,
        presence: true,
        length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
        
    validates :password,
        presence: true,
        length: { minimum: 6 }
        
    has_secure_password
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    def show
        @account = Account.find(params[:id])

    end 
    def new
        @account = Account.new
    end
    
    def index
        @accounts = Account.all
    end
    
    def edit
        @account = Account.find(params[:id])
    end
    
    def update
        @account = Account.find(params[:id]) 
        if @account.update(account_params)
            redirect_to @account 
        else
            render 'edit' 
        end
    end
    
    def destroy
        @account = Account.find(params[:id]) 
        
        @account.destroy
            redirect_to accounts_path 
    end
    

    
    def create
        @account = Account.new(account_params)
        @account.user = current_user
        
        
        if @account.save 
            redirect_to @account
        else
            render 'new'
        end
    
    end 

    
end



    private 
        def account_params
            params.require(:account).permit(:goal,:time,:motivation,:plan,:hoursPerDay,:daysPerWeek)
        end   

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    def current_user
        if session[:user_id]
            @current_user || User.find(session[:user_id])
        else
            @current_user = nil
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def index
            # render template: "pages/#{params[:id]}"
            render "pages/show.html.erb"

end
def create
    render "pages/show.html.erb"
end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Welcome to FitFun! Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid! Please try it again!"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out! Hope to see you soon!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/edit.html.erb
<!--Social media icons-->
    <link rel='stylesheet prefetch' href='https://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!--Wallpaper and navigation bar-->
        <div class = "wallpaper1">
            
            <nav class="nav">
                <!--Logo image-->
                
                    
                    
                        
                    
                    
                
                
                <% if current_user %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Log out', logout_path%>
                 <% else %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Login', login_path%>
                <% end %>
        

            </nav>
            <%= link_to welcome_index_path do %>
                       <%= image_tag "", id: "logo" %>
                        <% end %>
             
        </div><!--End wallpaper and navigation bar-->
        
        
<h1>Editing Account</h1>
 
<%= form_for :account, url: account_path(@account), method: :patch do |a| %>
 
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@account.errors.count, "error") %> prohibited
        this account from being saved:
      </h2>
      <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <fieldset>
    <legend>Form</legend>
    <div class= "form">
        
        <h3 class="form-title">User information: </h3>
        
        
        <p class="input-form">
            <%= a.label :goal,  "Goal" %><br>
           <%= a.text_field :goal %>
        </p>
        
        <p class="input-form">
            <%= a.label :time, "Time to finish the goal:" %><br>
            <%= a.text_field :time %>
        </p>
        
        <p class="input-form">
            <%= a.label :motivation, "Your motivation:" %><br>
            <%= a.text_field :motivation %>
        </p>
        
        <p class="input-form">
            <%= a.label :plan, "Tell us your plan:" %><br>
            <%= a.text_field :plan %>
        </p>
        
        <p class="input-form">
            <%= a.label :hoursPerDay, "How many hour(s)/day: " %><br>
            <%= a.text_field :hoursPerDay %>
        </p>
        
        
       
        <p class="input-form">
            <%= a.label :daysPerWeek, "How many day(s)/week: " %><br>
           <%= a.text_field :daysPerWeek %>
        </p>
        
        
        
        
       
        <p class= "submitButton">
            <a><%= a.submit %></a>
        </p>
    </div>
</fieldset>
<% end %>

<!--Footer-->
                <footer class="main-footer">
                    <div class="footer-col" >
                        <!--Social media icon-->
                        <div class="social-icon">
                            <a href="https://twitter.com" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
                            <a href="https://facebook.com" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
                            <a href="https://plus.google.com" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
                        </div>

                        <!--Our mission part-->
                        <div class="our-mission" >
                            <h2>Our mission</h2>
                            
                        </div>

                        <!--Contact button and google map-->
                        <div class="text-button">
                            <!--Map-->
                            <div class="mapouter">
                                <div class="gmap_canvas">
                                    <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=unc%20charlotte&t=&z=13&ie=UTF8&iwloc=&output=embed" >
                                    </iframe>
                                </div>
                            </div>


                        </div>

                    </div>


                    <!--Copy right-->
                    <div id="footer-bottom">
                        <hr>
                        <a href="#top">Back to top &raquo;</a>
                        <p>All rights reserved.</p>
                        <p>&copy;Copyright 2019. All other trademarks and copyrights are the
                            property of their respective holders..</p>
                    </div>
                </footer>

app/views/accounts/index.html.erb
<!--Social media icons-->
    <link rel='stylesheet prefetch' href='https://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!--Wallpaper and navigation bar-->
        <div class = "wallpaper1">
            
            <nav class="nav">
                <!--Logo image-->
                
                    
                    
                   
                
                
                <% if current_user %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Log out', logout_path%>
                 <% else %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Login', login_path%>
                <% end %>
                        
        

            </nav>
            
              <%= link_to welcome_index_path do %>
                   <%= image_tag "", id: "logo" %>
                    <% end %>
                    
        </div><!--End wallpaper and navigation bar-->
<h1>
    Listing Goals
</h1>



    <% if current_user %>
    <h3 class="note">Hello <%= current_user.name %>, never stop reaching your goals!</h1>
    <div class="button">
        <%= link_to 'New Goal', new_account_path%>
    </div>
<table>
  <tr>
    <th>User</th>
    <th>Goal</th>
    <th>Time</th>
    <th>Motivation</th>
    <th>Tell us your plan</th>
    <th>How many hour(s)/day</th>
    <th>How many day(s)/week</th>
    
    
  </tr>
 
  <% @accounts.each do |a| %>
    <tr>
    <td><% if a.user %>
        <%= a.user.name %>
        <% end %>
    </td>
      <td><%= a.goal %></td>
      <td><%= a.time %></td>
      <td><%= a.motivation %></td>
      <td><%= a.plan %></td>
      <td><%= a.hoursPerDay %></td>
      <td><%= a.daysPerWeek %></td>
      
      
          <td class="button button_with_no_border"><%= link_to 'Show', account_path(a) %></td>
      
          <td class="button button_with_no_border"><%= link_to 'Edit', edit_account_path(a) %></td>
          
          <td class="button button_with_no_border"><%= link_to 'Destroy',
                account_path(a),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
    
    </tr>
  <% end %>
</table>
                            <% else %>
                                <h3 class="note">Hello, Please login before checking your goals</h1>
                                <div class="button center"><%= link_to "Log In", login_path %></div>
                            <% end %> 


<!--Footer-->
                <footer class="main-footer">
                    <div class="footer-col" >
                        <!--Social media icon-->
                        <div class="social-icon">
                            <a href="https://twitter.com" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
                            <a href="https://facebook.com" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
                            <a href="https://plus.google.com" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
                        </div>

                        <!--Our mission part-->
                        <div class="our-mission" >
                            <h2>Our mission</h2>
                            
                        </div>

                        <!--Contact button and google map-->
                        <div class="text-button">
                            <!--Map-->
                            <div class="mapouter">
                                <div class="gmap_canvas">
                                    <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=unc%20charlotte&t=&z=13&ie=UTF8&iwloc=&output=embed" >
                                    </iframe>
                                </div>
                            </div>


                        </div>

                    </div>


                    <!--Copy right-->
                    <div id="footer-bottom">
                        <hr>
                        <a href="#top">Back to top &raquo;</a>
                        <p>All rights reserved.</p>
                        <p>&copy;Copyright 2019. All other trademarks and copyrights are the
                            property of their respective holders..</p>
                    </div>
                </footer>

app/views/accounts/show.html.erb
<!--Social media icons-->
    <link rel='stylesheet prefetch' href='https://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!--Wallpaper and navigation bar-->
        <div class = "wallpaper1">
            
            <nav class="nav">
                <!--Logo image-->
                
                    
                    

                 <% if current_user %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Log out', logout_path%>
                 <% else %>

                 <%= link_to 'About', pages_path %>

                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Login', login_path%>
                <% end %>
                
                
                        
        

            </nav>
            <%= link_to welcome_index_path do %>
                   <%= image_tag "", id: "logo" %>
                    <% end %>
        </div><!--End wallpaper and navigation bar-->
<p>
    <strong>Goal: </strong>
    <%= @account.goal %>
</p>

<p>
    <strong>Time to finish the goal(s) in day(s): </strong>
    <%= @account.time %>
</p>

<p>
    <strong>Your Motivation: </strong>
    <%= @account.motivation%>
</p>

<p>
    <strong>Tell us your plan: </strong>
    <%= @account.plan %>
</p>
<p>
    <strong>How many hour(s)/day: </strong>
    <%= @account.hoursPerDay %>
</p>
<p>
    <strong>How many day(s)/week: </strong>
    <%= @account.daysPerWeek %>
</p>


<!--Footer-->
                <footer class="main-footer">
                    <div class="footer-col" >
                        <!--Social media icon-->
                        <div class="social-icon">
                            <a href="https://twitter.com" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
                            <a href="https://facebook.com" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
                            <a href="https://plus.google.com" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
                        </div>

                        <!--Our mission part-->
                        <div class="our-mission" >
                            <h2>Our mission</h2>
                            
                        </div>

                        <!--Contact button and google map-->
                        <div class="text-button">
                            <!--Map-->
                            <div class="mapouter">
                                <div class="gmap_canvas">
                                    <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=unc%20charlotte&t=&z=13&ie=UTF8&iwloc=&output=embed" >
                                    </iframe>
                                </div>
                            </div>


                        </div>

                    </div>


                    <!--Copy right-->
                    <div id="footer-bottom">
                        <hr>
                        <a href="#top">Back to top &raquo;</a>
                        <p>All rights reserved.</p>
                        <p>&copy;Copyright 2019. All other trademarks and copyrights are the
                            property of their respective holders..</p>
                    </div>
                </footer>

app/views/users/edit.html.erb
<!--Social media icons-->
    <link rel='stylesheet prefetch' href='https://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!--Wallpaper and navigation bar-->
        <div class = "wallpaper">
            
            <nav class="nav">
                
                
                
                <% if current_user %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Log out', logout_path%>
                 <% else %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Login', login_path%>
                <% end %>
                        
                        
        

            </nav>
            <!--Logo image-->
                    <%= link_to welcome_index_path do %>
                       <%= image_tag "", id: "logo" %>
                        <% end %>
        </div><!--End wallpaper and navigation bar-->


<div class="login-form">
    <h1>Editing User</h1>

    <%= render 'form', user: @user %>
    
    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>
</div>





<!--Footer-->
                <footer class="main-footer">
                    <div class="footer-col" >
                        <!--Social media icon-->
                        <div class="social-icon">
                            <a href="https://twitter.com" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
                            <a href="https://facebook.com" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
                            <a href="https://plus.google.com" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
                        </div>

                        <!--Our mission part-->
                        <div class="our-mission" >
                            <h2>Our mission</h2>
                            
                        </div>

                        <!--Contact button and google map-->
                        <div class="text-button">
                            <!--Map-->
                            <div class="mapouter">
                                <div class="gmap_canvas">
                                    <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=unc%20charlotte&t=&z=13&ie=UTF8&iwloc=&output=embed" >
                                    </iframe>
                                </div>
                            </div>


                        </div>

                    </div>


                    <!--Copy right-->
                    <div id="footer-bottom">
                        <hr>
                        <a href="#top">Back to top &raquo;</a>
                        <p>All rights reserved.</p>
                        <p>&copy;Copyright 2019. All other trademarks and copyrights are the
                            property of their respective holders..</p>
                    </div>
                </footer>

app/views/users/index.html.erb
<!--Social media icons-->
    <link rel='stylesheet prefetch' href='https://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!--Wallpaper and navigation bar-->
        <div class = "wallpaper">
            
            <nav class="nav">
                
                
                
                <% if current_user %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Log out', logout_path%>
                 <% else %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Login', login_path%>
                <% end %>
                        
                        
        

            </nav>
            <!--Logo image-->
                    <%= link_to welcome_index_path do %>
                       <%= image_tag "", id: "logo" %>
                        <% end %>
        </div><!--End wallpaper and navigation bar-->



<div class="login-form">
  <p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
</div>





<!--Footer-->
                <footer class="main-footer">
                    <div class="footer-col" >
                        <!--Social media icon-->
                        <div class="social-icon">
                            <a href="https://twitter.com" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
                            <a href="https://facebook.com" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
                            <a href="https://plus.google.com" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
                        </div>

                        <!--Our mission part-->
                        <div class="our-mission" >
                            <h2>Our mission</h2>
                            
                        </div>

                        <!--Contact button and google map-->
                        <div class="text-button">
                            <!--Map-->
                            <div class="mapouter">
                                <div class="gmap_canvas">
                                    <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=unc%20charlotte&t=&z=13&ie=UTF8&iwloc=&output=embed" >
                                    </iframe>
                                </div>
                            </div>


                        </div>

                    </div>


                    <!--Copy right-->
                    <div id="footer-bottom">
                        <hr>
                        <a href="#top">Back to top &raquo;</a>
                        <p>All rights reserved.</p>
                        <p>&copy;Copyright 2019. All other trademarks and copyrights are the
                            property of their respective holders..</p>
                    </div>
                </footer>

app/views/users/show.html.erb
<!--Social media icons-->
    <link rel='stylesheet prefetch' href='https://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!--Wallpaper and navigation bar-->
        <div class = "wallpaper">
            
            <nav class="nav">
                
                
                
                <% if current_user %>
                <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Log out', logout_path%>
                 <% else %>
                 <%= link_to 'About', pages_path %>
                 <%= link_to 'User',new_account_path%>
                <%= link_to 'User Info', accounts_path %> 
                <div id="lesson_nav"><%= link_to 'Lesson', welcome_index_path %></div>  
                <%= link_to 'Login', login_path%>
                <% end %>
                        
                        
        

            </nav>
            <!--Logo image-->
                    <%= link_to welcome_index_path do %>
                       <%= image_tag "", id: "logo" %>
                        <% end %>
        </div><!--End wallpaper and navigation bar-->


                  <div class="login-form">
                    <p id="notice"><%= notice %></p>
                  
                  <p>
                    <strong>Name:</strong>
                    <%= @user.name %>
                  </p>
                  
                  <p>
                    <strong>Email:</strong>
                    <%= @user.email %>
                  </p>
                  
                  <p>
                    <strong>Gender:</strong>
                    <%= @user.gender %>
                  </p>
                  
                  <%= link_to 'Edit', edit_user_path(@user) %> |
                  <%= link_to 'Back', users_path %>
                  </div>
                  




<!--Footer-->
                <footer class="main-footer">
                    <div class="footer-col" >
                        <!--Social media icon-->
                        <div class="social-icon">
                            <a href="https://twitter.com" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
                            <a href="https://facebook.com" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
                            <a href="https://plus.google.com" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
                        </div>

                        <!--Our mission part-->
                        <div class="our-mission" >
                            <h2>Our mission</h2>
                            
                        </div>

                        <!--Contact button and google map-->
                        <div class="text-button">
                            <!--Map-->
                            <div class="mapouter">
                                <div class="gmap_canvas">
                                    <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=unc%20charlotte&t=&z=13&ie=UTF8&iwloc=&output=embed" >
                                    </iframe>
                                </div>
                            </div>


                        </div>

                    </div>


                    <!--Copy right-->
                    <div id="footer-bottom">
                        <hr>
                        <a href="#top">Back to top &raquo;</a>
                        <p>All rights reserved.</p>
                        <p>&copy;Copyright 2019. All other trademarks and copyrights are the
                            property of their respective holders..</p>
                    </div>
                </footer>